In [1]:
# Import NumPy as its abbreviation 'np'

import numpy as np


In [17]:

# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1,2,3,4])
arr

# Create a 2-dimensional NumPy array using np.array()
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
type(arr1)
arr1.shape
print(arr1.ndim)

# Create a 3-dimensional Numpy array using np.array()
arr2 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])
arr2.ndim


2


3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array. 

In [14]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(type(arr))

(4,)
1
int32
4
<class 'numpy.ndarray'>


In [15]:
# Attributes of 2-dimensional array

print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)
print(type(arr1))

(2, 4)
2
int32
8
<class 'numpy.ndarray'>


In [18]:
# Attributes of 3-dimensional array
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(type(arr2))


(2, 3, 3)
3
int32
18
<class 'numpy.ndarray'>


In [25]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

new_df = pd.DataFrame(arr1)
new_df



0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [28]:
#Create an array of shape (10, 2) with only ones

ones_arr = np.ones((10,2))
ones_arr.shape

(10, 2)

In [31]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((7,2,3))
zeros_arr
zeros_arr.shape

(7, 2, 3)

In [32]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0,100,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [35]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random = np.random.randint(0,10, size=(7,2))
arr_random

array([[8, 5],
       [4, 5],
       [3, 7],
       [6, 1],
       [5, 9],
       [5, 2],
       [3, 7]])

In [38]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_arr = np.random.random(size=(3,5))
float_arr

array([[0.03529968, 0.64849126, 0.5025254 , 0.08996714, 0.53724174],
       [0.65528423, 0.82716464, 0.90749129, 0.39007049, 0.38048352],
       [0.39823733, 0.70449373, 0.54484825, 0.44011488, 0.91303737]])

In [46]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.randint(0,10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
Are the numbers in the array different or the same? Why do think this is?

R/ porque hemos fijado seed = 42

In [53]:
#Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

rd_num = np.random.randint(0,10, size=(3,7))
print(rd_num)
print('')
#Find the unique numbers in the array you just created
print(np.unique(rd_num))


[[2 6 5 7 8 4 0]
 [2 9 7 5 7 8 3]
 [0 0 9 3 6 1 2]]

[0 1 2 3 4 5 6 7 8 9]


In [54]:
# Find the 0'th index of the latest array you created

rd_num[0]

array([2, 6, 5, 7, 8, 4, 0])

In [57]:

# Get the first 2 rows of latest array you created


rd_num[:2]


array([[2, 6, 5, 7, 8, 4, 0],
       [2, 9, 7, 5, 7, 8, 3]])

In [59]:

# Get the first 2 values of the first 2 rows of the latest array
rd_num[:2, :2]

array([[2, 6],
       [2, 9]])

In [81]:
#Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rdm_arr = np.random.random(size=(3,5))
ones_array = np.ones((3,5))

print(rdm_arr)
print(ones_array)

[[0.89855419 0.60642906 0.00919705 0.10147154 0.66350177]
 [0.00506158 0.16080805 0.54873379 0.6918952  0.65196126]
 [0.22426931 0.71217922 0.23724909 0.3253997  0.74649141]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
#Add the two arrays together

arr_sum = rdm_arr + ones_array

In [72]:
# Create another array of ones of shape (5, 3)
one_arr = np.ones((5,3))

In [82]:
# Try add the array of ones and the other most recent array together

res_arr = rdm_arr + one_arr



ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error.  
Why do think this is?
How would you fix it?


In [75]:
# Create another array of ones of shape (3, 5)
new_ones_arr = np.ones((3,5))


In [18]:
# Subtract the new array of ones from the other most recent array
new_arr2 = new_ones_arr + arr_sum
new_arr2

NameError: name 'new_ones_arr' is not defined

In [ ]:
# Multiply the ones array with the latest array


In [ ]:
# Take the latest array to the power of 2 using '**'

In [ ]:
# Do the same thing with np.square()


In [1]:
# Find the mean of the latest array using np.mean()
import numpy as np
arr_q = np.array([1,2,3,4,5,6])
arr_q


array([1, 2, 3, 4, 5, 6])

In [2]:
# Find the maximum of the latest array using np.max()
np.max(arr_q)

6

In [3]:
# Find the minimum of the latest array using np.min()
np.min(arr_q)

1

In [4]:
# Find the standard deviation of the latest array
np.std(arr_q)

1.707825127659933

In [5]:
# Find the variance of the latest array
np.var(arr_q)

2.9166666666666665

In [33]:
arr_rs = np.array([[[1,2,3,4,5],
                   [6,7,8,9,10],
                 [11,12,13,14,34]],
                   
                 [[15,16,17,18,45],
                  [19,20,21,43,32],
                  [23,54,45,23,22]],
                   
                  [[24,54,43,76,76],
                    [25,13,75,86,54],
                    [26,87,43,45,55]]])
arr_rs.shape


(3, 3, 5)

In [34]:
# Reshape the latest array to (3, 5, 1)
arr_rs = arr_q.reshape(3,5,1)
arr_rs

ValueError: cannot reshape array of size 6 into shape (3,5,1)

In [35]:
# Transpose the latest array

arr_rs

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 34]],

       [[15, 16, 17, 18, 45],
        [19, 20, 21, 43, 32],
        [23, 54, 45, 23, 22]],

       [[24, 54, 43, 76, 76],
        [25, 13, 75, 86, 54],
        [26, 87, 43, 45, 55]]])



What does the transpose do?


In [40]:
# Create two arrays of random integers between 0 to 10
arr1 = np.random.randint(10, size=(3,3))
arr2 = np.random.randint(10, size=(3,2))
print(arr1)
print(arr2)
# one of size (3, 3) the other of size (3, 2)


[[8 4 4]
 [9 3 6]
 [7 7 5]]
[[6 2]
 [4 8]
 [9 9]]


In [43]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)
res_arr

array([[100,  84],
       [120,  96],
       [115, 115]])

In [47]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
math1 = np.random.randint(10, size=(4,3))
math2 = np.random.randint(10,size=(4,3))
math1.shape, math2.shape


((4, 3), (4, 3))

In [48]:
# Perform a dot product on the two newest arrays you created
np.dot(math1,math2)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)



It doesn't work. How would you fix it?


In [49]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both

np.dot(math1,math2.T)


array([[ 40,  81, 131,  40],
       [ 35,  67, 112,  33],
       [ 19,  45,  66,  23],
       [ 19,  55,  76,  25]])



Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on np.dot() may help, as well as reading Math is Fun's guide on the dot product.

Let's now compare arrays.


In [58]:
# dot product: example del profe Alex (youtube)

a = np.array([[5,3,-4,-2],
             [8,-1,0,-3]])
a.shape

ba = np.random.randint(10, size=(4,3))
b = np.array([[1,4,0],
             [-5,3,7],
             [0,-9,5],
             [5,1,4]])
b.shape

dot_prod = np.dot(a,b)
dot_prod

array([[-20,  63,  -7],
       [ -2,  26, -19]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [ ]:
# Compare the two arrays with '>'


What happens when you compare the arrays with >?

In [ ]:


# Compare the two arrays with '>='


In [ ]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:


# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100



Extensions

For more exercises, check out the NumPy quickstart tutorial. A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the Stack Overflow page for the top questions and answers for NumPy. Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.
