## PyTorch Course!
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
print("Hello I'm exiting to learn PyTorch! ")

Hello I'm exiting to learn PyTorch! 


In [ ]:
!nvidia-smi

Thu Mar 23 05:40:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    27W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

# PyTorch version:
print(torch.__version__)

1.13.1+cu116


## Introduction to tensors

Creating tensors:

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector.ndim
vector

tensor([7, 7])

## Day 2
PyTorch Introduction....

In [ ]:
# MATRIX

MATRIX = torch.tensor([[5,1,2,3,4],
          [4,5,6,7,8]])
MATRIX

tensor([[5, 1, 2, 3, 4],
        [4, 5, 6, 7, 8]])

In [ ]:
MATRIX.ndim
MATRIX[0], MATRIX[1]

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [ ]:
MATRIX.shape

torch.Size([2, 5])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3,4,5,6],
                        [5,7,8,7,3,7],
                        [8,3,5,2,0,9]]])
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 6])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3, 4, 5, 6],
        [5, 7, 8, 7, 3, 7],
        [8, 3, 5, 2, 0, 9]])

# RANDOM TENSORS
# Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
# The shape of the tensor is defined by the variable argument size.

In [ ]:
RANDOM_TENSOR = torch.rand(5,10, 5)
RANDOM_TENSOR

tensor([[[0.2110, 0.1294, 0.7416, 0.2935, 0.0167],
         [0.5266, 0.3029, 0.6070, 0.2515, 0.4045],
         [0.6868, 0.4292, 0.0589, 0.1996, 0.8117],
         [0.2645, 0.2473, 0.1408, 0.8943, 0.9829],
         [0.3956, 0.1505, 0.0870, 0.7689, 0.2781],
         [0.7377, 0.9142, 0.5835, 0.0819, 0.7838],
         [0.0102, 0.7266, 0.2454, 0.2045, 0.9860],
         [0.0551, 0.7294, 0.3099, 0.3313, 0.5396],
         [0.8539, 0.7754, 0.8854, 0.5779, 0.0787],
         [0.1488, 0.9642, 0.5309, 0.0190, 0.6183]],

        [[0.4652, 0.1891, 0.7688, 0.0021, 0.5227],
         [0.3533, 0.3259, 0.2196, 0.4993, 0.5323],
         [0.9153, 0.9921, 0.0619, 0.5097, 0.7680],
         [0.6596, 0.2701, 0.9094, 0.5434, 0.0236],
         [0.1677, 0.9447, 0.7773, 0.4957, 0.6259],
         [0.5744, 0.0876, 0.5252, 0.4213, 0.7925],
         [0.5267, 0.6855, 0.6362, 0.0227, 0.9596],
         [0.2732, 0.6118, 0.7680, 0.2220, 0.9927],
         [0.3356, 0.3887, 0.8502, 0.2665, 0.2219],
         [0.8008, 0.2663, 0.6

In [ ]:
RANDOM_TENSOR.shape

torch.Size([5, 10, 5])

In [ ]:
# random tensor ith similar shapeto an image:

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, idth, colour channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Zeros and ones

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones  

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

In [ ]:
# Creating a range of tensors

ts = torch.range(0,11)
ts

<ipython-input-66-1657591299c8>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ts = torch.range(0,11)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
# Using arange:
import torch

arange_tensor = torch.arange(start=10, end=1000, step=100)
arange_tensor

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [15]:
arange_tensor_2 = torch.arange(10, 1000, 100)
arange_tensor_2

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [16]:
# tensors like:

ts_like = torch.ones_like(arange_tensor)
ts_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### **Tensor datatypes**

In [26]:
# float 32 tensor:

tensor_float_32 = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
tensor_float_32.dtype

torch.float16

In [27]:
float_16_tensor = tensor_float_32.type(torch.float32)
float_16_tensor.dtype 

torch.float32

In [29]:
tensor_float_32 * float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

####  Getting tensor atributtes:


In [50]:
rand_tensor = torch.rand(4, 7,
                         device="cuda")
rand_tensor

tensor([[0.7657, 0.9218, 0.9538, 0.7125, 0.6773, 0.0522, 0.8498],
        [0.0381, 0.7919, 0.3175, 0.1059, 0.8655, 0.2447, 0.3714],
        [0.0062, 0.5135, 0.2185, 0.6818, 0.0920, 0.1572, 0.1273],
        [0.8352, 0.8984, 0.5437, 0.0707, 0.0679, 0.0698, 0.0243]],
       device='cuda:0')

In [36]:
rand_tensor.size(), rand_tensor.dtype

(torch.Size([4, 7]), torch.float32)

In [52]:
# details:
import subprocess
def tensor_info(tensor):

  print(tensor)
  print(f"Tensor datatype -> {tensor.dtype}")
  print(f"Shape[size] of Tensor -> {tensor.size()}")
  print(f"Shape of Tensor -> {tensor.shape}")
  print(f"Device tensor is on: {tensor.device}")
  gpu_info = subprocess.check_output(['nvidia-smi'])
  print("Device information: ", gpu_info.decode('utf-8'))

tensor_info(rand_tensor)


tensor([[0.7657, 0.9218, 0.9538, 0.7125, 0.6773, 0.0522, 0.8498],
        [0.0381, 0.7919, 0.3175, 0.1059, 0.8655, 0.2447, 0.3714],
        [0.0062, 0.5135, 0.2185, 0.6818, 0.0920, 0.1572, 0.1273],
        [0.8352, 0.8984, 0.5437, 0.0707, 0.0679, 0.0698, 0.0243]],
       device='cuda:0')
Tensor datatype -> torch.float32
Shape[size] of Tensor -> torch.Size([4, 7])
Shape of Tensor -> torch.Size([4, 7])
Device tensor is on: cuda:0
Device information:  Mon Mar 27 06:02:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+==