## PyTorch Course!
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
print("Hello I'm exiting to learn PyTorch! ")

Hello I'm exiting to learn PyTorch! 


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

# PyTorch version:
print(torch.__version__)

2.0.0+cu118


## Introduction to tensors

Creating tensors:

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector.ndim
vector

tensor([7, 7])

## Day 2
PyTorch Introduction....

In [ ]:
# MATRIX

MATRIX = torch.tensor([[5,1,2,3,4],
          [4,5,6,7,8]])
MATRIX

tensor([[5, 1, 2, 3, 4],
        [4, 5, 6, 7, 8]])

In [ ]:
MATRIX.ndim
MATRIX[0], MATRIX[1]

(tensor([5, 1, 2, 3, 4]), tensor([4, 5, 6, 7, 8]))

In [ ]:
MATRIX.shape

torch.Size([2, 5])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3,4,5,6],
                        [5,7,8,7,3,7],
                        [8,3,5,2,0,9]]])
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 6])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3, 4, 5, 6],
        [5, 7, 8, 7, 3, 7],
        [8, 3, 5, 2, 0, 9]])

# RANDOM TENSORS
# Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
# The shape of the tensor is defined by the variable argument size.

In [ ]:

RANDOM_TENSOR = torch.rand(5,10, 5)
RANDOM_TENSOR

tensor([[[0.1142, 0.6430, 0.3321, 0.5565, 0.9961],
         [0.0262, 0.9891, 0.3165, 0.6044, 0.8220],
         [0.2713, 0.7156, 0.7549, 0.0475, 0.9079],
         [0.2696, 0.2641, 0.4001, 0.9202, 0.0382],
         [0.0760, 0.4682, 0.4512, 0.2452, 0.1841],
         [0.3886, 0.2623, 0.0962, 0.5644, 0.0717],
         [0.2434, 0.1539, 0.7645, 0.8477, 0.8225],
         [0.7818, 0.9476, 0.8078, 0.9580, 0.9250],
         [0.9915, 0.2279, 0.6083, 0.0241, 0.1759],
         [0.8574, 0.2774, 0.3891, 0.5145, 0.1148]],

        [[0.7985, 0.3444, 0.9386, 0.5123, 0.4444],
         [0.7399, 0.2332, 0.5983, 0.6724, 0.9643],
         [0.9998, 0.8204, 0.4098, 0.4348, 0.4231],
         [0.1365, 0.7147, 0.8809, 0.4228, 0.4854],
         [0.3575, 0.2785, 0.1214, 0.7432, 0.9766],
         [0.0523, 0.4514, 0.2753, 0.2673, 0.0841],
         [0.5009, 0.7645, 0.5419, 0.3743, 0.4856],
         [0.2365, 0.9338, 0.7024, 0.5391, 0.2146],
         [0.7136, 0.7856, 0.2829, 0.9979, 0.9889],
         [0.7866, 0.2521, 0.5

In [ ]:
RANDOM_TENSOR.shape

torch.Size([5, 10, 5])

In [ ]:
# random tensor ith similar shapeto an image:

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, idth, colour channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Zeros and ones

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones  

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

In [ ]:
# Creating a range of tensors

ts = torch.range(0,11)
ts

<ipython-input-48-1657591299c8>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ts = torch.range(0,11)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# Using arange:
import torch

arange_tensor = torch.arange(start=10, end=1000, step=100)
arange_tensor

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [ ]:
arange_tensor_2 = torch.arange(10, 1000, 100)
arange_tensor_2

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [ ]:
# tensors like:

ts_like = torch.ones_like(arange_tensor)
ts_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### **Tensor datatypes**

In [ ]:
# float 32 tensor:

tensor_float_32 = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
tensor_float_32.dtype

torch.float16

In [ ]:
float_16_tensor = tensor_float_32.type(torch.float32)
float_16_tensor.dtype 

torch.float32

In [ ]:
tensor_float_32 * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

####  Getting tensor atributtes:


In [ ]:
# import torch
# rand_tensor = torch.rand(4, 7,
#                          device="cuda")
# rand_tensor

In [ ]:
rand_tensor.size(), rand_tensor.dtype

NameError: ignored

In [ ]:
# details:
import subprocess
def tensor_info(tensor):

  print(tensor)
  print(f"Tensor datatype -> {tensor.dtype}")
  print(f"Shape[size] of Tensor -> {tensor.size()}")
  print(f"Shape of Tensor -> {tensor.shape}")
  print(f"Device tensor is on: {tensor.device}")
  gpu_info = subprocess.check_output(['nvidia-smi'])
  print("Device information: ", gpu_info.decode('utf-8'))

tensor_info(rand_tensor)


In [ ]:
# Manipulating TENSORS (Tensor operations)

### **PyTorch in-built functions!**

In [ ]:
tensor = torch.tensor([33, 14, 2023])
tensor

In [ ]:
tensor_mul = torch.mul(tensor, 2)
tensor_mul

## **01/abril/2023**
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Element wise mult
import torch
tensor = torch.tensor([1,2,3])
print("{} '*' {} ".format(tensor, tensor))

print(f"Equals: {tensor * tensor}")

In [ ]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

In [ ]:
# Matrix multiplication by hand:
tensor

In [ ]:
mat_mul_by_hand = 1*1 + 2*2 + 3*3
mat_mul_by_hand

**Por que?**  
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
%%time

value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(f" The value is: {value}")

NameError: ignored

In [ ]:
%%time
# en datasets enormes, se recomienda usar built-in fn de Pytorch
torch.matmul(tensor,tensor)


There are two main rules that performing matrix multp needs to satisfy:  
1. The **inner dimensions** must match.
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work



In [ ]:
# Common error:

torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: ignored

2. The resulting matrix has the shape of the **outer dimensions**.  
`(2,3) @ (3,2)` -> `(2,2)`  
`(3,2) @ (2,3)` -> `(3,3)`


# One of the most common errors in ***deep learning***: **shape errors**

In [ ]:
import torch
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# A transpose switches the axes or dimensions of a given tensor.
# https://pytorch.org/docs/stable/generated/torch.transpose.html#torch.transpose

# tensor_B = tensor_B.T

tensor_A.shape, tensor_B.shape

# torch.mm(tensor_A, tensor_B)

In [ ]:
print(f"Tensor B sin T: {tensor_B}\n"  
      f"\n Tensor B T: {tensor_B.T}")

In [ ]:
tensor_A.shape, tensor_B.shape

torch.mm(tensor_A, tensor_B.T)


### The matrix multiplication operations works when **tensor_B** is transposed. 

In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print(f"\n Output: \n")
result = torch.mm(tensor_A, tensor_B.T)
print(result)
print(f"\n Output shape: {result.shape} \n")


## Finding the `mean, min, max, sum`, etc **(tensor aggregation)**

In [ ]:
# Create a tensor:

x = torch.arange(start=0, end=100, step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean:

torch.mean(x.type(torch.float)), x.type(torch.float).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Returns the indices of the maximum and minimum values of all elements in the input tensor.

torch.argmin(x), x.argmin(), torch.argmax(x), x.argmax()

(tensor(0), tensor(0), tensor(9), tensor(9))

### Reshaping, stacking, squeezing, unsqueezing tensors:  
**A veces es necesario cambiar la forma de un tensor para poder realizar ciertas operaciones.**

* Reshaping (remodelado) Cambia la forma de un tensor manteniendo el mismo número total de elementos. 
Por ejemplo, si tienes un tensor de forma (3, 4) que contiene 12 elementos, 
puedes remodelarlo en un tensor de forma (4, 3) que también contiene 12 elementos. La operación de remodelado no cambia los datos en sí, solo cambia la forma en que se organizan.

* Stacking (apilado):   Combina varios tensores a lo largo de una nueva dimensión. Por ejemplo, si tienes dos tensores de forma (3, 4) y los apilas a lo largo de la dimensión 0, obtendrás un tensor de forma (2, 3, 4). La operación de apilado es útil cuando se quiere combinar datos de múltiples fuentes.

* Squeezing (comprimir):   Elimina las dimensiones de tamaño 1 de un tensor. Por ejemplo, si tienes un tensor de forma (1, 3, 1, 4), puedes comprimirlo en un tensor de forma (3, 4) mediante la eliminación de las dimensiones de tamaño 1. La operación de compresión se utiliza para simplificar la forma de un tensor.

* Unsqueezing (descomprimir):   Agrega dimensiones de tamaño 1 a un tensor existente. Por ejemplo, si tienes un tensor de forma (3, 4), puedes descomprimirlo en un tensor de forma (1, 3, 1, 4) mediante la adición de dimensiones de tamaño 1. La operación de descompresión es útil cuando se quiere cambiar la forma de un tensor para poder realizar operaciones que requieren una dimensión adicional.

In [ ]:
import torch

x = torch.arange(1. ,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_two = torch.arange(1., 10.)
x_reshaped_two = x_two.reshape(1,9)
x_reshaped_two

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_3 = torch.arange(1, 11)
x_3.shape

x_3_reshaped = x_3.reshape(5,2)
x_3_reshaped

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

### ***Change the view***

In [ ]:
import torch

x = torch.arange(1. ,10.)
x, x.shape

v = x.view(1,9)
v , v.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

### Changing z changes x **(because a view of a tensor shares the same memory as the original tensor)**

In [ ]:
v[:, 0] = 5
x, v

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

## Stack tensors on top of each other

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
import torch

# Creamos una lista de tensores de forma (2,)
t1 = torch.tensor([1, 2])
t2 = torch.tensor([3, 4])
t3 = torch.tensor([5, 6])
tensor_list = [t1, t2, t3]

# Usamos torch.stack para concatenar la lista de tensores a lo largo de una nueva dimensión
stacked_tensor = torch.stack(tensor_list, dim=0)

print("tensor_list: \n", tensor_list )
print("\n stacked_tensor: ", stacked_tensor)


tensor_list: 
 [tensor([1, 2]), tensor([3, 4]), tensor([5, 6])]

 stacked_tensor:  tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# .squeeze() -> PyTorch docs:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [ ]:
# torch.squeeze() -> Removes all single dimensions from a target tensor
print(f"Previous tensor {v}")
print(f"Previous shape {v.shape}")

# remove extra dimensions
v_squeezed = v.squeeze()
print(f"New tensor {v_squeezed}")
print(f"Previous shape {v_squeezed.shape}")


Previous tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape torch.Size([1, 9])
New tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape torch.Size([9])


In [ ]:
# torch.unsqueeze(): adds a sinlge dimension to a target tensor at a specific dimension
x = torch.tensor([1, 2, 3, 4])
x.shape

x, torch.unsqueeze(x, 0), torch.unsqueeze(x, 1)

(tensor([1, 2, 3, 4]),
 tensor([[1, 2, 3, 4]]),
 tensor([[1],
         [2],
         [3],
         [4]]))

In [ ]:
print(f"Previous target: {v}")
print(f"Previous shape: {v.shape}")
print("")
v_unsqueezed = v.unsqueeze(dim=0)
print(f"\n New tensor: {v_unsqueezed}")
print(f"Previous shape: {v_unsqueezed.shape}")

Previous target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


 New tensor: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
Previous shape: torch.Size([1, 1, 9])


## Returns a view of the original tensor input with its dimensions permuted.
**No cambia el tensor, solo lo reasigna tal y como queramos**  
*Parameters:*

        input (Tensor) – the input tensor.

        dims (tuple of python:int) – The desired ordering of dimensions



In [ ]:
x = torch.randn(2, 3, 5)
print('X:', x)



X: tensor([[[ 0.0544,  0.0941, -0.8067, -0.7289,  1.1259],
         [ 0.7818,  0.7628,  0.0813, -0.7516, -1.9001],
         [ 0.1012, -1.3748, -0.4291, -0.2659, -0.6971]],

        [[-0.1670,  0.0446, -1.1380,  0.6405,  0.8444],
         [ 0.7593, -1.1280,  2.6799,  0.0169,  1.2478],
         [-0.1156,  1.4532, -1.2461,  0.0612,  3.3290]]])


In [ ]:
x_permuted = torch.permute(x, (2,0,1))
x_permuted

tensor([[[ 0.0544,  0.7818,  0.1012],
         [-0.1670,  0.7593, -0.1156]],

        [[ 0.0941,  0.7628, -1.3748],
         [ 0.0446, -1.1280,  1.4532]],

        [[-0.8067,  0.0813, -0.4291],
         [-1.1380,  2.6799, -1.2461]],

        [[-0.7289, -0.7516, -0.2659],
         [ 0.6405,  0.0169,  0.0612]],

        [[ 1.1259, -1.9001, -0.6971],
         [ 0.8444,  1.2478,  3.3290]]])

In [ ]:
# torch.permute - rearreanges the dimesnions of a target tensor in a specific order
import torch

x_original = torch.rand(size=(224,224,3)) #[height, widht, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_perm = x_original.permute(2,0,1) 

# This function prints the shape of two PyTorch tensors, before and after
# reshaping them. The tensors must have the same number of dimensions.
# Arguments:
# - prev: the original tensor
# - next: the reshaped tensor

def shapeView(prev, next):
    assert isinstance(prev, torch.Tensor) and isinstance(next, torch.Tensor)
    assert prev.dim() == next.dim()
    
    # Print the original shape and the new shape
    print(f"Previous shape: {prev.shape}")
    print(f"New shape: {next.shape}")
    

In [ ]:
shapeView(prev=x_original, next=x_perm)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Indexing *(selecting data from tensors)*** 

In [ ]:
import torch

x = torch.arange(1, 10)
# x, x.shape

# reshape the tensor 
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0][1], x[0,2] # equals to x[0][2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,2,2]
x[0,2,2]

x[:,:,2].T

tensor([[3],
        [6],
        [9]])

## PyTorch tensors & **NumPy**

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# warning: el valor por defecto de numpy es float.64, hay que tener cuidado con eso.
# el valor por defecto de PyTorch es float.32

In [ ]:
tensor.dtype, tensor.type(torch.float32).dtype


(torch.float64, torch.float32)

In [ ]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## ***PyTorch Reproducibility***  
https://pytorch.org/docs/stable/notes/randomness.html

In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)




tensor([[0.6120, 0.0378, 0.6707, 0.2527],
        [0.8893, 0.8918, 0.7285, 0.8424],
        [0.9831, 0.0907, 0.4239, 0.2937]])
tensor([[0.9010, 0.5801, 0.0957, 0.4915],
        [0.9060, 0.5025, 0.1618, 0.9175],
        [0.9076, 0.5439, 0.6374, 0.9571]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_TENSOR = 42

torch.manual_seed(RANDOM_TENSOR)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

!nvidia-smi

Fri Apr  7 05:11:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# setup device agnostic code

device = 'cuda' if torch.cuda.is_available() else 'CPU'
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## CUDA best practices:  
`https://pytorch.org/docs/stable/notes/cuda.html`

In [ ]:
# move tensor to GPU (if available)

tensor = torch.tensor([1,2,3])

tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# Si el tensor esta en la GPU, no se puede transformar a NUMPY
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# Para arreglarlo, debemos primero configurarlo en la CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])